name: Generate HMAC Signature for OKX

on:
  repository_dispatch:
    types: [generate-signature]

jobs:
  generate-signature:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run HMAC Script
        env:
          PREHASH: ${{ github.event.client_payload.prehash }}  # Input del prehash desde Make
          SECRET_KEY: ${{ secrets.OKX_SECRET_KEY }}  # Tu secret key (agrega en repo Settings > Secrets)
        run: |
          python hmac_signer.py

      - name: Output Signature
        id: signature
        run: echo "sign=$(python -c 'import hmac, base64, hashlib; print(base64.b64encode(hmac.new(\"$SECRET_KEY\".encode(), \"$PREHASH\".encode(), hashlib.sha256).digest()).decode())')" >> $GITHUB_OUTPUT

      - name: Send Response
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: 'success',
              description: 'HMAC Generated',
              target_url: 'https://api.github.com/repos/$$ {{ github.repository }}/actions/runs/ $${{ github.run_id }}',
              context: 'HMAC Signature'
            });
            // Opcional: Webhook de respuesta a Make via HTTP POST (ver abajo)